### ISSUE TITLE
vector of pairs with reference

### ISSUE THREAD

**Issue by matanmarkind** [gfx/cpp-TimSort#16]
Hi, I seem to be having an issue with pairs. I start with a vector with 4 elements
(1,a) (3,c) (4,d) (2,b) 
But then when I try to sort them I get 'd' being repeated and 'b' is gone
(1,a) (2,d) (3,c) (4,d) 
This doesn't happen when the second value in the pair is a string (I want a string&). Here is the code I use

```cpp
int main() {
  typedef std::pair<int, std::string&> KV;
  std::vector<KV> keys;
  keys.reserve(8);
  std::vector<std::string> vals;
  vals.reserve(8);
  vals.push_back("a");
  keys.push_back(static_cast<KV>(KV(1, vals.back())));
  vals.push_back("c");
  keys.push_back(static_cast<KV>(KV(3, vals.back())));
  vals.push_back("d");
  keys.push_back(static_cast<KV>(KV(4, vals.back())));
  vals.push_back("b");
  keys.push_back(static_cast<KV>(KV(2, vals.back())));
  std::cout << std::endl;
  for (auto s : keys) {
    std::cout << "(" << s.first << "," << s.second << ") ";
  }
  std::cout << std::endl;
  timsort(keys.begin(),
                 keys.end(),
                 [](const KV& a, const KV& b) {
                   return a.first < b.first;
                 });
  for (auto s : keys) {
    std::cout << "(" << s.first << "," << s.second << ") ";
  }
  std::cout << std::endl;
  return 0;
}
```

**Comment by gfx** [comment]
I have reproduced this issue whereas `std::sort()` works as expected. Will investigate it.

**Comment by matanmarkind** [comment]
Actually std::sort is giving me the same error. Maybe we have different compilers? I'm using g++ 5.4 on ubuntu 16.04

**Comment by gfx** [comment]
What the!? I'm using clang++ on macOS. If `std::sort()` fails with the same error, the bug could be somewhere in the standard libraries. OMG.

**Comment by matanmarkind** [comment]
What do you mean? I don't touch the vals vector after the insertions, so all the memory should be in the same location. 

Why does it matter if an element of the pair is a reference or not? Shouldn't the sorting algorithm just move the pair without regard for what the details inside are (except for the comparator)? Remember it works fine before sorting, so vals.back() certainly seems to do what I want.

**Comment by matanmarkind** [comment]
Hi so I went back and redid some of this. It turns out that when I sort the keys, it in fact is overwriting the vals vector. So the sorting happens, and the reference is to the right element in vals, but now the second element in vals is also a d. Everything works fine if I switch to using a pointer instead of a reference in the pair for both std::sort and timsort. Let me know if you understand what's going on. 

Even though this issue exists, since std::stable_sort does the same thing it might make sense to close this.

**Comment by Morwenn** [comment]
Actually the behaviour you're looking for indeed does work with pointers, but when you perform a `swap` on a pair with a reference, the reference isn't changed: the the values referred to are swapped, which is probably what you're witnessing.

It isn't a bug, it's just that references aren't the right tool to handle the problem :)

**Comment by matanmarkind** [comment]
Thanks Morwenn. Is this because references are basically an alias for the actual value whereas pointers need to be explicitly dereferenced to get to their underlying value? If swap works on the values why aren't the underlying value just swapped?

**Comment by Morwenn** [comment]
Sometimes, instead of swapping, algorithms move values around and sometimes store them into temporaries, let's have a look at the following code:

    int main()
    {
        std::string sa = "a";
        std::string sb = "b";
        
        std::pair<int, std::string&> pa = { 1, sa };
        std::pair<int, std::string&> pb = { 2, sb };
        
        auto tmp = std::move(pa);
        pa = std::move(pb);
        pb = std::move(tmp);
        
        std::cout << pa.second << ' ' << pb.second;
    }

Here, `tmp` has a reference to `sa` when constructed, then `pa = std::move(pb)` overrides `sa` with `sb` because `pa.second` is a reference. At this point `tmp.second == pa.second == pb.second == sb` and the original value of `sa` has been overriden by that of `sb`, so the final `pb = std::move(sb)` just replaces `sb` with itself.

Honestly, a the end of the day, the value of `sa` should even be undefined because it has been moved from by the line `pb = std::move(sb)`. I think it doesn't crash because the string is super small and so it takes advantage of the Small String Optimization (that's speculative).

**Comment by matanmarkind** [comment]
Alright, thanks so much for the help.

**Comment by Morwenn** [comment]
My pleasure :)
