### ISSUE TITLE
Formal verification issue

### ISSUE THREAD

**Issue by mattreecebentley** [gfx/cpp-TimSort#23]
Just a question, has this implementation address the 2015 issue found during formal verification?
https://en.wikipedia.org/wiki/Timsort#Formal_verification

I'm not familiar enough with the algorithm to tell, at this stage.

**Comment by gfx** [comment]
I'm not sure butif it is the isssue suggested in http://envisage-project.eu/proving-android-java-and-python-sorting-algorithm-is-broken-and-how-to-fix-it/, I got a pull-request for it: https://github.com/gfx/cpp-TimSort/pull/6 (related to #5).

**Comment by mattreecebentley** [comment]
Yes, that's the one. Cool - good to know.
