### ISSUE TITLE
support vector of pairs

### ISSUE THREAD

**Issue by degenkolb** [gfx/cpp-TimSort#3]
Hi

I found your implementation of tim sort via a stackoverflow question. 
Would it be possible to support vector of pairs in your code?
Currently I get the following compiler message when trying with a vector if <double, int> pairs.
```
error: no matching function for call to ‘timsort(std::vector<std::pair<double, int> >::iterator, <unresolved overloaded function type>)’
      gfx::timsort(vector_pair.begin(), vector_pair.end)
```
with regards
christian

**Comment by gfx** [comment]
Can you tell me more details? In fact, it has already test code for `std::vector<std::pair<...> >`: https://github.com/gfx/cpp-TimSort/blob/master/test/test.cpp#L480

I have no idea why your code doesn't work.

**Comment by gfx** [comment]
I got it. You must give a comparison function as the 3rd argument to `timsort()` just like as `std::sort()`. Can you give it a try?

**Comment by degenkolb** [comment]
You are absolutely right. With the comparison function it works like a charm. 
Thanks and sorry for the confusion.

**Comment by matanmarkind** [comment]
Hi, I seem to be having another issue with pairs. I start with a vector with 4 elements
(1,a) (3,c) (4,d) (2,b) 
But then when I try to sort them I get 'd' being repeated and 'b' is gone
(1,a) (2,d) (3,c) (4,d) 
This doesn't happen when the second value in the pair is a string (I want a string&). Here is the code I use

int main() {
  typedef std::pair<int, std::string&> KV;
  std::vector<KV> keys;
  keys.reserve(8);
  std::vector<std::string> vals;
  vals.reserve(8);
  vals.push_back("a");
  keys.push_back(static_cast<KV>(KV(1, vals.back())));
  vals.push_back("c");
  keys.push_back(static_cast<KV>(KV(3, vals.back())));
  vals.push_back("d");
  keys.push_back(static_cast<KV>(KV(4, vals.back())));
  vals.push_back("b");
  keys.push_back(static_cast<KV>(KV(2, vals.back())));
  std::cout << std::endl;
  for (auto s : keys) {
    std::cout << "(" << s.first << "," << s.second << ") ";
  }
  std::cout << std::endl;
  timsort(keys.begin(),
                 keys.end(),
                 [](const KV& a, const KV& b) {
                   return a.first < b.first;
                 });
  for (auto s : keys) {
    std::cout << "(" << s.first << "," << s.second << ") ";
  }
  std::cout << std::endl;
  return 0;
}
